---
- name: Add all clusters hosts to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }}.{{ hostvars[item]['domain'] }} {{ item }}"
    insertafter: EOF
  loop: "{{ groups['all'] }}"

- name: Comment the 127.0.0.1 line in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '127.0.0.1\t{{ inventory_hostname }}\.{{ domain }}'
    line: "# 127.0.0.1\t{{ inventory_hostname }}.{{ domain }}"
