---
- hosts: '*'
  connection: local
  become: True

  tasks:
    - name: Ensure root password is Vagrant
      user:
        name: root
        password: '{{ "vagrant" | password_hash("sha512", "salt123") }}'

    - name: Add Generated Public Key to Authorized Keys
      shell: cat /vagrant/files/tdp-rsa.pub >> /home/vagrant/.ssh/authorized_keys

    - name: Install core stack
      yum:
        name:
        - vim
        - java-1.8.0-openjdk
        - wget
        - curl
        - unzip
        - nc
        state: present

    - name: Set JAVA_HOME
      copy:
        content: JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk
        dest: /etc/environment

    - name: Restart network
      service:
        name: network
        state: restarted
        args: eth0
