---
- hosts: '*'
  connection: local
  become: True

  tasks:
    - name: Ensure root password is Vagrant
      user:
        name: root
        password: '{{ "vagrant" | password_hash("sha512", "salt123") }}'
  
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Install core stack
      yum:
        name:
        - vim
        - java-1.8.0-openjdk
        - wget
        - curl
        - unzip
        state: present