---
- hosts: '*'
  connection: local
  become: True

  tasks:
    - name: Ensure root password is Vagrant
      user:
        name: root
        password: '{{ "vagrant" | password_hash("sha512", "salt123") }}'

    - name: Update /etc/hosts with cluster info from /vagrant/tdp-hosts
      shell: grep -v '^\[' /vagrant/tdp-hosts | awk -F'[/= ]' '{print $3" "$1" "$9}' >> /etc/hosts
      become_user: root

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Install core stack
      yum:
        name:
        - vim
        - java-1.8.0-openjdk
        - wget
        - curl
        - unzip
        state: present