---
- hosts: localhost
  tasks:
    - name: Generate new ssh key locally
      import_role:
        name: ansible_roles/roles/ansible-ssh-deployment
        tasks_from: generate-user-ssh-keys

- hosts: all
  tasks:
    - name: Deploy public key
      import_role:
        name: ansible_roles/roles/ansible-ssh-deployment
        tasks_from: deploy-user-ssh-keys
