---
- hosts: kdc
  become: yes
  vars:
    realm_name: REALM.TDP
    kdc_port: 88
    master_db_pass: krb5-master-pass
    kadmin_user: admin/admin
    kadmin_pass: admin
    kdc_server: "{{ groups['kdc'][0] | tosit.tdp.access_fqdn(hostvars) }} "
    kadmind_server: "{{ groups['kdc'][0] | tosit.tdp.access_fqdn(hostvars) }}"
  tasks:
    - import_role:
        name: roles/ansible-kerberos-server

- hosts: kdc
  tasks:
    - name: Fetch krb5.conf to local files dir from kdc
      fetch:
        src: /etc/krb5.conf
        dest: files/
        flat: yes

- hosts: all
  become: yes
  vars:
    realm_name: REALM.TDP
    kdc_server: "{{ groups['kdc'][0] | tosit.tdp.access_fqdn(hostvars) }} "
    kadmind_server: "{{ groups['kdc'][0] | tosit.tdp.access_fqdn(hostvars) }}"
  tasks:
    - import_role:
        name: roles/ansible-kerberos-client
      tags: dhj
