- hosts: all
  vars:
    users:
      - tdp-user
  become: yes
  tasks:
  - name: Add unix users
    user:
      name: "{{item}}"
      home: "/home/{{item}}/"
      password: '{{ "{{item}}" | password_hash("sha512", "salt123") }}'
    with_items: "{{users}}"

  - name: Ensure user ~/.ssh exists
    file:
      path: "/home/{{item}}/.ssh/"
      state: directory
    with_items: "{{users}}"

  - name: Generate user principals and keytabs
    become: yes
    vars:
    - realm: REALM.TDP
    - kadmin_principal: admin/admin
    - kadmin_password: admin
    shell: |
      kadmin -r {{realm}} -p {{kadmin_principal}} -w {{kadmin_password}} -q "addprinc -randkey {{item}}/{{ ansible_fqdn }}@{{realm}}"
      kadmin -r {{realm}} -p {{kadmin_principal}} -w {{kadmin_password}} -q "xst -k {{item}}.principal.keytab {{item}}/{{ ansible_fqdn }}@{{realm}}"
      chown {{item}}:{{item}} {{item}}.principal.keytab
    args:
      chdir: /home/{{item}}/.ssh/
      creates: /home/{{item}}/.ssh/{{item}}.principal.keytab
    with_items: "{{users}}"
