---
- hosts: localhost
  tasks:

  - name: Create directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
    - logs
    - files

  - name: Create ansible log file
    copy:
      content: ""
      dest: logs/tdp.log
      force: yes

  - name: Create vagrant log file
    copy:
      content: ""
      dest: logs/vagrant.log
      force: yes

  - name: Clone ansible KDC role
    ansible.builtin.git:
      repo: git@github.com:DanielJohnHarty/ansible-kerberos-server.git
      dest: roles/ansible-kerberos-server
      accept_hostkey: yes
      force: yes

  - name: Clone ansible kerberos client role
    ansible.builtin.git:
      repo: git@github.com:DanielJohnHarty/ansible-kerberos-client.git
      dest: roles/ansible-kerberos-client
      accept_hostkey: yes
      force: yes

  - name: Clone TDP ansible roles
    ansible.builtin.git:
      repo: git@github.com:TOSIT-FR/ansible-tdp-roles.git
      dest: collections/ansible_collections/tosit/tdp
      accept_hostkey: yes
      force: yes

  - name: Clone ansible-ca role
    ansible.builtin.git:
      repo: git@github.com:DanielJohnHarty/ansible-create-ca.git
      dest: roles/ansible-ca
      accept_hostkey: yes
      force: yes

  - name: Clone postgres role
    ansible.builtin.git:
      repo: git@github.com:geerlingguy/ansible-role-postgresql.git
      dest: roles/ansible-role-postgresql
      accept_hostkey: yes
      force: no
      force: yes

  - name: Check ssh key exists
    stat:
      path: files/tdp-rsa
    register: ssh_key_exists
    tags:
      - ssh-key-gen

  - name: Generate ssh keys if missing
    shell: | 
      ssh-keygen -t rsa  -b 2048 -f files/tdp-rsa -P "" -C "tdp"
      chmod 600 files/tdp-rsa
      chmod 600 files/tdp-rsa.pub
    when: ssh_key_exists.stat.exists == false
    tags:
      - ssh-key-gen

  - name: Install pip packages
    pip:
      name:
        - jmespath

  - name: Spawn Virtual Machines Logging Information
    shell: "vagrant up  2>&1 | tee -a logs/vagrant.log"


