---
- name: Deploy Hadoop
  become: yes
  hosts: hdfs_nn:hdfs_jn:hdfs_dn:yarn_rm:yarn_nm:hadoop_client
  gather_facts: true
  tasks:
    - import_role:
        name: tosit.tdp.hadoop
      tags: install

- name: Hadoop cluster bootstrap
  hosts: localhost
  become: yes
  gather_facts: no
  tasks:
    - import_role:
        name: tosit.tdp.hadoop
        tasks_from: post_install.yml
      tags: post-install
