---
- hosts: localhost
  tasks:
  - name: Check zookeeper binary exists
    stat:
      path: files/zookeeper-3.4.6.tar.gz
    register: zk_exists
  - name: Download zookeeper binary to files if missing
    shell: wget https://archive.apache.org/dist/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz -P files
    when: zk_exists.stat.exists == False

- hosts: zk
  become: yes
  vars:
    - realm: TDP
    - kadmin_principal: admin/admin
    - kadmin_password: admin
    - suffix: :2888:3888
    - zk_ips: "{{groups['zk'] | map('extract', hostvars, ['ansible_host']) | list}}"
    - zk_servers: "{{ zk_ips | product([suffix]) | map('join') | list }}"
  tasks:
    - import_role:
        name: tosit.tdp.zookeeper
  
    # - name: print zkerrber
    #   debug:
    #     msg: "{{zk_servers}}"
