---
- name: Deploy users
  hosts: all
  become: yes
  tasks:
    - name: Create unix user 
      user:
        name: "{{item.username}}"
        home: "/home/{{item.username}}/"
        password: '{{ "{{item.password}}" | password_hash("sha512", "salt123") }}'
      with_items: "{{users}}"
    - name: Ensure user ~/.ssh exists
      file:
        path: "/home/{{item.username}}/.ssh/"
        state: directory
      with_items: "{{users}}"
    - name: Generate user principals and keytabs
      become: yes
      shell: |
        kadmin -r {{realm}} -p {{kadmin_principal}} -w {{kadmin_password}} -q "addprinc -randkey {{item.username}}/{{ ansible_fqdn }}@{{realm}}"
        kadmin -r {{realm}} -p {{kadmin_principal}} -w {{kadmin_password}} -q "xst -k {{item.username}}.principal.keytab {{item.username}}/{{ ansible_fqdn }}@{{realm}}"
        chown {{item.username}}:{{item.username}} {{item.username}}.principal.keytab
      args:
        chdir: /home/{{item.username}}/.ssh/
        creates: /home/{{item.username}}/.ssh/{{item.username}}.principal.keytab
      with_items: "{{users}}"

- name: Create user hdfs dir
  hosts: hdfs_nn[0]
  become: yes
  tasks:
  - name: Kinit for hdfs
    become: yes
    become_user: "{{ hdfs_user }}"
    command: "kinit -kt /etc/security/keytabs/nn.service.keytab nn/{{ groups['hdfs_nn'][0] | tosit.tdp.access_fqdn(hostvars) }}@{{ realm }}"
  - name: Create user hdfs folders
    become: yes
    become_user: "{{ hdfs_user }}"
    tosit.tdp.hdfs_file:
      hdfs_conf: "{{ hadoop_conf_dir }}"
      path: "/user/{{ item.username }}"
      state: directory
      owner: "{{ item.username }}"
      group: "{{ item.username }}"
      mode: "755"
    loop: "{{ users }}"

- name: Create users in ranger
  hosts: ranger_admin[0]
  become: yes
  tasks:
    - include_role:
        name: ansible_roles/roles/ansible-tdp-common-actions
        tasks_from: deploy-new-ranger-user
      with_items:
        - "{{ users }}"

- name: Create hdfs user access policies in ranger
  hosts: ranger_admin[0]
  become: yes
  tasks:
    - include_role:
        name: ansible_roles/roles/ansible-tdp-common-actions
        tasks_from: deploy-ranger-hdfs-policy
      with_items:
        - "{{ user_hdfs_policies }}"

- name: Deploy ranger hive policies in ranger
  hosts: ranger_admin[0]
  become: yes
  tasks:
    - include_role: 
        name: ansible_roles/roles/ansible-tdp-common-actions
        tasks_from: deploy-ranger-hive-policy
      with_items:
        - "{{ user_hive_policies }}"