---
- hosts: localhost
  vars:
  - realm: REALM.TDP
  - kadmin_principal: admin/admin
  - kadmin_password: admin
  tasks:
    - name: Check ranger binary exists
      stat:
        path: files/ranger-2.0.1-TDP-0.1.0-SNAPSHOT-admin.tar.gz
      register: rg_exists
      failed_when: not rg_exists.stat.exists

- hosts: postgresql
  become: yes
  tasks:
    - name: Create rangeradmin user if not exists
      become_user: postgres
      shell: psql -tc "SELECT 1 FROM pg_user WHERE usename = 'rangeradmin'" | grep -q 1 || (echo "CREATE USER rangeradmin WITH PASSWORD 'rangeradmin';" | psql -U postgres)
      tags: pgchu
    - name: Create ranger database if it doesn't exist already
      become_user: postgres
      shell: psql -tc "SELECT 1 FROM pg_database WHERE datname = 'ranger'" | grep -q 1 || (echo "CREATE DATABASE ranger;" | psql -U postgres)
      tags: pgchu
    - name: Grant all privileges to rangeradmin user on ranger database
      become_user: postgres
      shell: echo "GRANT ALL PRIVILEGES ON DATABASE ranger TO rangeradmin;" | psql -U postgres
      tags: pgchu

- hosts: ranger_admin
  become: yes
  tasks:
    - import_role: 
        name: tosit.tdp.ranger
      vars:
        ranger_jdbc_connector_package: postgresql-jdbc
        realm: REALM.TDP
        kadmin_principal: admin/admin
        kadmin_password: admin
        install_properties:
          #setup_mode: postgres
          db_host: "{{groups['postgresql'][0] | tosit.tdp.access_fqdn(hostvars) }}:5432"
          db_user: rangeradmin
          db_password: rangeradmin
          DB_FLAVOR: postgres
          db_name: ranger
          audit_store: db # deprecated but keeps the setup.sh script from requesting a solr endpoint
          SQL_CONNECTOR_JAR: /usr/share/java/postgresql-jdbc.jar
          db_root_user: postgres
          db_root_password: postgres
      tags: rapb

- hosts: hdfs_nn
  become: yes
  vars:
    - realm: REALM.TDP
    - kadmin_principal: admin/admin
    - kadmin_password: admin
    - ranger_admin_password: RangerAdmin123
  tasks:
    - import_role:
        name: tosit.tdp.hadoop
        tasks_from: ranger_hdfs_plugin
      tags: hdfspi

- hosts: yarn_rm
  become: yes
  vars:
    - realm: REALM.TDP
    - kadmin_principal: admin/admin
    - kadmin_password: admin
    - ranger_admin_password: RangerAdmin123
  tasks:
    - import_role:
        name: tosit.tdp.hadoop
        tasks_from: ranger_yarn_plugin
      tags: yarnpi
