---
- hosts: localhost
  tasks:
  - name: Check zookeeper binary exists
    stat:
      path: files/zookeeper-3.4.6.tar.gz
    register: zk_exists
  - name: Download zookeeper binary to files if missing
    shell: wget https://archive.apache.org/dist/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz -P files
    when: zk_exists.stat.exists == False

- hosts: zk
  become: yes
  vars:
    - realm: TDP.REAL.OPENSOURCE
    - kadmin_principal: admin/admin
    - kadmin_password: admin
  tasks:
    - import_role:
        name: tosit.tdp.zookeeper
