---
- hosts: localhost
  tasks:
    - name: Check ranger binary exists
      stat:
        path: files/ranger-2.0.1-TDP-0.1.0-SNAPSHOT-admin.tar.gz
      register: rg_exists
      failed_when: not rg_exists.stat.exists

- hosts: postgresql
  become: yes
  tasks:
    - name: Create rangeradmin user if not exists
      become_user: postgres
      shell: psql -tc "SELECT 1 FROM pg_user WHERE usename = 'rangeradmin'" | grep -q 1 || (echo "CREATE USER rangeradmin WITH PASSWORD 'rangeradmin';" | psql -U postgres)
      tags: pgchu
    - name: Create ranger database if it doesn't exist already
      become_user: postgres
      shell: psql -tc "SELECT 1 FROM pg_database WHERE datname = 'ranger'" | grep -q 1 || (echo "CREATE DATABASE ranger;" | psql -U postgres)
      tags: pgchu
    - name: Grant all privileges to rangeradmin user on ranger database
      become_user: postgres
      shell: echo "GRANT ALL PRIVILEGES ON DATABASE ranger TO rangeradmin;" | psql -U postgres
      tags: pgchu

- hosts: ranger_admin
  become: yes
  tasks:
    - import_role: 
        name: tosit.tdp.ranger
      tags: rapb

- hosts: hdfs_nn
  become: yes
  tasks:
    - import_role:
        name: tosit.tdp.hadoop
        tasks_from: ranger_hdfs_plugin
      tags: hdfspi

- hosts: yarn_rm
  become: yes
  tasks:
    - import_role:
        name: tosit.tdp.hadoop
        tasks_from: ranger_yarn_plugin
      tags: yarnpi
