---
- hosts: localhost
  tasks:

  - name: Create directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
    - logs
    - files

  - name: Create log file
    copy:
      content: ""
      dest: logs/tdp-getting-started.log
      force: no

  - name: Spawn Virtual Machines
    shell: "vagrant up"

  - name: Clone ansible KDC role
    ansible.builtin.git:
      repo: https://github.com/DanielJohnHarty/ansible-kerberos-server.git
      dest: roles/ansible-kerberos-server
      force: yes

  - name: Clone ansible kerberos client role
    ansible.builtin.git:
      repo: https://github.com/DanielJohnHarty/ansible-kerberos-client.git
      dest: roles/ansible-kerberos-client
      force: yes

  - name: Clone TDP ansible roles
    ansible.builtin.git:
      repo: https://github.com/TOSIT-FR/ansible-tdp-roles.git
      dest: collections/ansible_collections/tosit/tdp

  - name: Check ssh key exists
    stat:
      path: files/tdp-getting-started-rsa
    register: ssh_key_exists
    tags:
      - ssh-key-gen

  - name: Generate ssh keys if missing
    shell: | 
      ssh-keygen -t rsa  -b 2048 -f files/tdp-getting-started-rsa -P "" -C "tdp-getting-started"
      chmod 600 files/tdp-getting-started-rsa
      chmod 600 files/tdp-getting-started-rsa.pub
    when: ssh_key_exists.stat.exists == false
    tags:
      - ssh-key-gen

  - name: Set ssh key permission to 600
    shell: "chmod 600 {{item}}"
    with_items: 
      - files/tdp-getting-started-rsa
      - files/tdp-getting-started-rsa.pub
