---
# Certificate Authority location
ca_home_dir: /etc/security/ca

# Certificates location
cert_dir: '{{ ca_home_dir }}/certs'

# Certificate Authority informations
country_name: FR
state_or_province_name: Hauts-de-France
locality_name: Dunkerque
organization_name: ArcelorMittal France
organizational_unit_name: Direction de la Transformation Digitale
common_name: AM France Certificate Authority
email_address: admin@amf.com

# FQDNs of the certificates to generate
certs_fqdns: {}