---

- name: Check if Certificate Authority dir already exists
  stat:
    path: '{{ ca_home_dir }}'
  register: dir

- name: Create Certificate Authority dir {{ ca_home_dir }}
  file:
    path: '{{ ca_home_dir }}'
    state: directory
  when: not dir.stat.exists

- name: Upload the Certificate Authority configuration file
  template:
    src: ca.cnf.j2
    dest: '{{ ca_home_dir }}/arcelormittalfr-ca.cnf'
  when: not dir.stat.exists

- name: Create database and serial file
  shell:
    chdir: '{{ ca_home_dir }}'
    cmd: |
      echo 01 > serial.txt
  when: not dir.stat.exists

- name: Generate the Certificate Authority
  shell:
    chdir: '{{ ca_home_dir }}'
    cmd: openssl req -x509 -config arcelormittalfr-ca.cnf -newkey rsa:4096 -sha256 -nodes -out ca_cert.pem -keyout ca_key.pem -outform PEM -batch
  when: not dir.stat.exists

- name: Download Certificate Authority public cert to localhost
  fetch:
    src: '{{ ca_home_dir }}/ca_cert.pem'
    dest: files/certs/
    flat: yes