---
# Ranger web ui admin login
ranger_admin_user: admin
ranger_admin_password: RangerAdmin123

ranger_jdbc_connector_package: postgresql-jdbc
install_properties:
  DB_FLAVOR: postgres
  SQL_CONNECTOR_JAR: /usr/share/java/postgresql-jdbc.jar
  db_host: "{{groups['postgresql'][0] | tosit.tdp.access_fqdn(hostvars) }}:5432"
  db_name: ranger
  db_user: rangeradmin
  db_password: rangeradmin
